## Problem Statement:  task is to predict whether a passenger was transported to an alternate dimension during the Spaceship Titanic's collision with the spacetime anomaly

```train.csv - Personal records for about two-thirds (~8700) of the passengers, to be used as training data.```

contained Columns : ```1. PassengerId``` 2. ```HomePlanet ``` 3.```CryoSleep``` 4. ```Cabin``` 5. ```Destination ```6. ```Age``` 7. ```VIP``` 8.```RoomService, FoodCourt, ShoppingMall, Spa, VRDeck ``` .etc

### Instrection to Followed:
1. Require Library
2. Inspection the data

In [7]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

# Use the kagglehub client library to attach Kaggle resources like competitions, datasets, and models to your session
# Learn more about kagglehub: https://github.com/Kaggle/kagglehub/blob/main/README.md

import kagglehub
# kagglehub.dataset_download('<owner>/<dataset-slug>')

/kaggle/input/competitions/spaceship-titanic/sample_submission.csv
/kaggle/input/competitions/spaceship-titanic/train.csv
/kaggle/input/competitions/spaceship-titanic/test.csv

# 1. Require Library

In [8]:
#Import the library which we needed 
import pandas as pd 
import numpy as np

the data which contain 14 columns and each of them have different info we use ```df = data_frame ``` it will hold the all the record.

In [9]:
df = pd. read_csv('/kaggle/input/competitions/spaceship-titanic/train.csv')

In [10]:
df.head()

,PassengerId,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported
0,0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,False
1,0002_01,Earth,False,F/0/S,TRAPPIST-1e,24.0,False,109.0,9.0,25.0,549.0,44.0,Juanna Vines,True
2,0003_01,Europa,False,A/0/S,TRAPPIST-1e,58.0,True,43.0,3576.0,0.0,6715.0,49.0,Altark Susent,False
3,0003_02,Europa,False,A/0/S,TRAPPIST-1e,33.0,False,0.0,1283.0,371.0,3329.0,193.0,Solam Susent,False
4,0004_01,Earth,False,F/1/S,TRAPPIST-1e,16.0,False,303.0,70.0,151.0,565.0,2.0,Willy Santantines,True

In [18]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8693 entries, 0 to 8692
Data columns (total 14 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   PassengerId   8693 non-null   object
 1   HomePlanet    8492 non-null   object
 2   CryoSleep     8476 non-null   object
 3   Cabin         8494 non-null   object
 4   Destination   8511 non-null   object
 5   Age           8514 non-null   float64
 6   VIP           8490 non-null   object
 7   RoomService   8512 non-null   float64
 8   FoodCourt     8510 non-null   float64
 9   ShoppingMall  8485 non-null   float64
 10  Spa           8510 non-null   float64
 11  VRDeck        8505 non-null   float64
 12  Name          8493 non-null   object
 13  Transported   8693 non-null   bool
dtypes: bool(1), float64(6), object(7)
memory usage: 891.5+ KB
None

In [25]:
print(df.dtypes.value_counts())

object     7
float64    6
bool       1
Name: count, dtype: int64

the data type for each columns : 
```e
object is : 7
float : 6
bool : 1 
will see is there any way that e can change the float into int

In [11]:
def null_value(data):
    missing_count = data.isnull().sum()
    missing_per = missing_count / len(data)*100
    result = pd.DataFrame({'Missing_count':missing_count , 'Missing%':missing_per})
    return result[result['Missing_count']>0].sort_values(by='Missing_count', ascending=False)

In [12]:
null_value(df)

              Missing_count  Missing%
CryoSleep               217  2.496261
ShoppingMall            208  2.392730
VIP                     203  2.335212
HomePlanet              201  2.312205
Name                    200  2.300702
Cabin                   199  2.289198
VRDeck                  188  2.162660
FoodCourt               183  2.105142
Spa                     183  2.105142
Destination             182  2.093639
RoomService             181  2.082135
Age                     179  2.059128

In [17]:
df.shape[1]

14